### ISSUE TITLE
The "1-1" DFLC file keeps disappearing

### ISSUE THREAD

**Issue by SamuelSHrk** [riolubruh/SplitLargeFiles#12]
Whenever I upload an audio file so some sort (between 8MB or 25MB) I would get the "0-1" file but the "1-1" file disappears, rendering the audio file incomplete and unassembled.

https://github.com/user-attachments/assets/4ca1d8e1-ce9b-4877-9aff-aa7d338dfefa

**Comment by SamuelSHrk** [comment]
DLFC file, whatever

**Comment by riolubruh** [comment]
Assuming this is the problem I already know about, the file disappearing is only visual. The file can be downloaded/reconstructed by right-clicking the message and clicking "Download Large File". The code responsible for visually merging split files is only partially functional. I have tried to fix it, but Discord has changed the code for rendering attachments so much that most of the original code regarding it no longer works, and I didn't write it (since it came from ImTheSquid) so it's a pain to try to fix.

**Comment by SamuelSHrk** [comment]
> Assuming this is the problem I already know about, the file disappearing is only visual. The file can be downloaded/reconstructed by right-clicking the message and clicking "Download Large File". The code responsible for visually merging split files is only partially functional. I have tried to fix it, but Discord has changed the code for rendering attachments so much that most of the original code regarding it no longer works, and I didn't write it (since it came from ImTheSquid) so it's a pain to try to fix.

So you are saying there is nothing you can do to circumvent this issue.

**Comment by riolubruh** [comment]
It has been fixed.
